travis:
  secure:
    BINSTAR_TOKEN: olQRg2mb51t6ukSa+NhPIyDHCTlv4EJf5XeSrp5xOWrZdg8lH6dZOu9Qqb10SezSVh+Psm69GfafPOjPBu2e8tC2svAY1K/9xoKK4z1rLQxlRbcsqU8PRwpfHapBuno9jxg0kSyHAXu5V0DQfITevmXaxal+ED/+pOY9ooE62hSkKOnWIS13IzP/Dsa7YB8lhRZ49rwX8tgzMCBp+R8HGhMIxp5Uo27OP+rGMjUi9hQEkQ1FhZZBZEP02S6jjqF112pgrH8O2Dae2Cc4lA2EjuExe03d3O1g3QLXyMo7j4viYDtFYzUAv2xwFMuY8/W4pKWwlG7oPeSWr5pbcc+IRU7FIqNt4H8Xq3oLqvLD9L2hNc3p0Pc1ijSnYl9LqzGekyLVJ2huK2NIej5TkSPLgDqaqPMvYpqCHWqRerZurMSHR758rMc+gMM7HSFGNa915tyAmvWlGCswuSHpks2rBsEBKhk88HbUAV8WmAZuuTCdI6ThwpDNY66tAxsEJkut2zyKN8vdLiMjYXA5TZJBNzzNEpN1WBCf0cMzo9UlVv/e6tFM+lZe1sP7Zn8Quw4d25EqZFqfoYLfx0Up+t5pEuiJW5AfdMl6oLosplP4Ug9+ftfmlaIxX8kF9dirNg0g7PI/jcmip592dRW4qaJEA1VQMYvjOJx1HbmE5rvS9SM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
