travis:
  secure:
    BINSTAR_TOKEN: 38gpER0yTEV+fA+krxCKTJrqr8TeThV/yTpPEoYESpbBT/umV81pF0TrL5YwsNsfBN5HLumni8hsT7DKtOaHQ/gKM5tHh8ssVsUd7erljY/juya6LFQWztOiVFJYujZr4NgsDvpuopG4BnIZnap/shWdRKr2ECD3BP7M+npk4Fb8Ihe/ttVzxdJyxQXreA0F1L26SRwbHLBkLOJW/O6rdKH17I0CbFPz91FftsYxoeGUw0cQ314YFjP0Xzd5rp0GU0x81YeP2c1zOI+2cGahG3ukLz/AWJHATnEzQkT+Euepp6ddhhUTiSN1FjsDrBryI1QEUBnqbK47vFVvBTauqAhSkaTjBMk15MWx7uChqxVjT1aigLs+o3hzPeyqWcZ5WNS8Q91wLjkxbWI/baWjHLv7AvK7abRghnfZpA573W6GMhuVgb7gUEC0kPnU224iQwoPsMGhGBFCzLpymgJhHesdSzzsH9OKsUTqfsbTAR3FBM3BpIaBHipHVQbi1+r3OiRnLrguhVcLndf2TvY8RF27SZ/ZxKmwC+/9mfLEvQ2WBwl0Ld/NGR1ovsPKql6k6E1pES/Ij6JEgvdocK+f3lEofBYi3kHYzA/UJC9Q043kuqY89OtklHK5+Rl+vmDmTkw3ACzoY9BbLT58LjP6RhzQwGTqynt5RXHkiK318ws=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
